[package]
name = "agents"
version = "0.1.0"
authors = ["Tiago Castro <tiago.castro@mayadata.io>"]
edition = "2018"

[[bin]]
name = "core"
path = "core/src/server.rs"

[[bin]]
name = "jsongrpc"
path = "jsongrpc/src/server.rs"

[lib]
name = "common"
path = "common/src/lib.rs"

[dependencies]
structopt = "0.3.23"
tokio = { version = "1.12.0", features = ["full"] }
tonic = "0.5.2"
futures = "0.3.17"
serde_json = "1.0.68"
async-trait = "0.1.51"
dyn-clonable = "0.9.0"
smol = "1.2.5"
snafu = "0.6.10"
lazy_static = "1.4.0"
humantime = "2.1.0"
state = "0.5.2"
rpc =  { path = "../../rpc"}
http = "0.2.5"
paste = "1.0.5"
common-lib = { path = "../../common" }
reqwest = "0.11.4"
parking_lot = "0.11.2"
itertools = "0.10.1"
git-version = "0.3.5"
grpc = { path = "../grpc" }

# Tracing
opentelemetry-jaeger = { version = "0.15.0", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = "0.15.0"
opentelemetry = { version = "0.16.0", features = ["rt-tokio-current-thread"] }
tracing = "0.1.28"
tracing-subscriber = "0.2.24"
tracing-futures = "0.2.5"
opentelemetry-semantic-conventions = "0.8.0"

[dev-dependencies]
composer = { path = "../../composer" }
ctrlp-tests = { path = "../../tests/tests-mayastor" }
actix-rt = "2.2.0"
actix-web = { version = "4.0.0-beta.9", features = ["rustls"] }
url = "2.2.2"
once_cell = "1.8.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
